# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Mon Apr 03 19:46:48 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("zs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infile_path = QtGui.QLineEdit(self.groupBox)
        self.infile_path.setObjectName("infile_path")
        self.horizontalLayout.addWidget(self.infile_path)
        self.change_infile_btn = QtGui.QPushButton(self.groupBox)
        self.change_infile_btn.setObjectName("change_infile_btn")
        self.horizontalLayout.addWidget(self.change_infile_btn)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.zaokr_btn = QtGui.QPushButton(self.centralwidget)
        self.zaokr_btn.setObjectName("zaokr_btn")
        self.gridLayout.addWidget(self.zaokr_btn, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outfile_path = QtGui.QLineEdit(self.groupBox_3)
        self.outfile_path.setObjectName("outfile_path")
        self.horizontalLayout_2.addWidget(self.outfile_path)
        self.change_outfile_btn = QtGui.QPushButton(self.groupBox_3)
        self.change_outfile_btn.setObjectName("change_outfile_btn")
        self.horizontalLayout_2.addWidget(self.change_outfile_btn)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kasujzero_box = QtGui.QCheckBox(self.groupBox_4)
        self.kasujzero_box.setObjectName("kasujzero_box")
        self.verticalLayout.addWidget(self.kasujzero_box)
        self.powrozb_box = QtGui.QCheckBox(self.groupBox_4)
        self.powrozb_box.setObjectName("powrozb_box")
        self.verticalLayout.addWidget(self.powrozb_box)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        self.menuO_programie = QtGui.QMenu(self.menubar)
        self.menuO_programie.setObjectName("menuO_programie")
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionO_programie = QtGui.QAction(MainWindow)
        self.actionO_programie.setObjectName("actionO_programie")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuO_programie.addAction(self.actionO_programie)
        self.menuPlik.addAction(self.actionOpen)
        self.menuPlik.addAction(self.actionSave)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionExit)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuO_programie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ZScal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plik wejściowy:", None, QtGui.QApplication.UnicodeUTF8))
        self.change_infile_btn.setText(QtGui.QApplication.translate("MainWindow", "Zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.zaokr_btn.setText(QtGui.QApplication.translate("MainWindow", "Wykonaj!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Plik wyjściowy:", None, QtGui.QApplication.UnicodeUTF8))
        self.change_outfile_btn.setText(QtGui.QApplication.translate("MainWindow", "Zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Ustawienia:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Użytki", None, QtGui.QApplication.UnicodeUTF8))
        self.kasujzero_box.setText(QtGui.QApplication.translate("MainWindow", "Zamień 0 na 1 ar", None, QtGui.QApplication.UnicodeUTF8))
        self.powrozb_box.setText(QtGui.QApplication.translate("MainWindow", "Usuń rozbieżności", None, QtGui.QApplication.UnicodeUTF8))
        self.menuO_programie.setTitle(QtGui.QApplication.translate("MainWindow", "Pomoc", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlik.setTitle(QtGui.QApplication.translate("MainWindow", "Plik", None, QtGui.QApplication.UnicodeUTF8))
        self.actionO_programie.setText(QtGui.QApplication.translate("MainWindow", "O programie", None, QtGui.QApplication.UnicodeUTF8))
        self.actionO_programie.setStatusTip(QtGui.QApplication.translate("MainWindow", "Informacje o programie", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Otwórz", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Wybierz plik", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Zakończ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Zamyka aplikację", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Zapisz jako", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Zapis do pliku", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

